// <auto-generated />
namespace Hack.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addeddatatoendosrments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addeddatatoendosrments));
        
        string IMigrationMetadata.Id
        {
            get { return "201510250243573_Added data to endosrments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
